### ISSUE TITLE
while running this code run time error occours: "stack-overflow"

### ISSUE THREAD

**Issue by shashankmishra091** [SaranshKejriwal/Abandoned_Object#2]
while running this code run time error occours: "stack-overflow"

**Comment by SaranshKejriwal** [comment]
Hi Shashank,

I'm afraid you'll have to be more specific. I doubt your error statement says "stack-overflow"

**Comment by shashankmishra091** [comment]
int main()
{
	Mat img, diff, back, aban(200, 200, CV_8UC1, Scalar(0)), sub;
	char chk = 0;
	VideoCapture cap("aban3.mp4");
	int count = 0;//to count number of frames
	int npixel = 100;//change this value to increase number of averaged pixels
	queue<int>colq;
	int col2[160][160];
	int sum2[160][160] = { 0 };
	float avgq2[160][160] = { 0 };
	int k = 0;
	queue<int>colq2[160][160];

stack-overflow error occours at run time in the last line of the above code "queue<int>colq2[160][160];
please guide to resolve this excecption.........!!!!!!!!!!!!!!
![abandoned](https://cloud.githubusercontent.com/assets/25284718/22505173/04695dbe-e8a0-11e6-9e41-5ff149e0959e.png)
"

**Comment by SaranshKejriwal** [comment]
Try reducing the 2d array size. Your issue happens to be machine specific, since the code runs on my machine just fine...If your error(s) persist, feel free to reach out on my email.

**Comment by shashankmishra091** [comment]
tried reducing the size of 2d arrays but didn't got any solution of that
excecption, can you please help me with another implementation.

Thanks & Regards
Shashank Mishra
9475510131

**Comment by SaranshKejriwal** [comment]
I've uploaded another repo that contains a purely openCV based implementation

**Comment by shashankmishra091** [comment]
have tried that code of yours it helped me.....was it in opencv2.

Thanks & Regards
Shashank Mishra
9475510131
